language: clojure
lein: lein2
before_script:
  - mongod --version
  - ./bin/ci/before_script.sh
script: lein2 do clean, javac, test
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
services:
  - mongodb
branches:
  only:
    - master
    - 2.1.x-stable
