language: clojure
sudo: required
lein: lein
before_script:
  - ./bin/ci/install_mongodb.sh
  - mongod --version
  - ./bin/ci/before_script.sh
script: lein do clean, javac, test
jdk:
  - oraclejdk8
  - oraclejdk9
services:
  - mongodb
branches:
  only:
    - master
    - 3.0.x-stable
